import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {planPeople,observeAccess} from '../skills/woia-people/scripts/people-plan.mjs';
const base=()=>({method:'context',actor:{authenticated:true,department:'people',authorized:true,current:true,scope:'org:test'},person_ref:'person:synthetic',scope:'org:test',correlation_id:'request:1',authority:{accepted:true,owner:'owner:test',evidence_ref:'decision:1',current:true,scope:'org:test',actions:['workforce.read']},source:{ref:'workforce:1',revision:'r1',status:'CURRENT',accepted:true,scope:'org:test'},fields:['role'],allowed_fields:['role']});
test('scoped plan preserves correlation and never executes or grants',()=>{const r=planPeople(base());assert.equal(r.result,'PLANNED_CONTRIBUTION');assert.equal(r.effect_executed,false);assert.equal(r.authority_granted,false);assert.equal(r.access_applied,false);assert.equal(r.correlation_id,'request:1');});
for(const [label,change] of [
 ['cross organization actor',i=>i.actor.scope='other'],['unauthorized actor',i=>i.actor.authorized=false],['stale actor',i=>i.actor.current=false],['missing actor',i=>delete i.actor],['wrong department',i=>i.actor.department='finance'],['unauthenticated',i=>i.actor.authenticated=false],['missing correlation',i=>delete i.correlation_id],['missing identity',i=>delete i.person_ref],['unaccepted authority',i=>i.authority.accepted=false],['stale authority',i=>i.authority.current=false],['scope mismatch',i=>i.authority.scope='other'],['wrong action',i=>i.authority.actions=[]],['missing evidence',i=>delete i.authority.evidence_ref],['unknown source',i=>i.source.status='UNKNOWN'],['stale source',i=>i.source.status='STALE'],['unaccepted source',i=>i.source.accepted=false],['source scope mismatch',i=>i.source.scope='other'],['restricted field',i=>i.fields.push('salary')],['external dispatch',i=>i.method='communication.external.send'],['access issue',i=>i.method='technology.access.apply']]) test(label+' fails closed',()=>{const i=base();change(i);assert.equal(planPeople(i).result,'BLOCKED');});
test('unknown effect requires reconciliation without retry',()=>{const i=base();i.effect_status='UNKNOWN';assert.equal(planPeople(i).result,'RECONCILE_REQUIRED');});
for(const method of ['joining','assignment','leaving','preparation','coverage']) test(method+' requires competent decision',()=>{const i=base();i.method=method;i.authority.actions=['workforce.onboarding.record','workforce.assignment.record','workforce.offboarding.record','workforce.competence.record','workforce.coverage.update'];assert.equal(planPeople(i).reason,'competent_decision_required');});
test('guidance requires approved versioned Knowledge',()=>{const i=base();i.method='guidance';i.authority.actions=['knowledge.read'];assert.equal(planPeople(i).result,'BLOCKED');i.source.approved=true;i.procedure_version='v1';assert.equal(planPeople(i).provider,'woia-organization-knowledge');});
test('coverage preserves preparation authority period acceptance and independent review',()=>{const i=base();i.method='coverage';i.decision_ref='d1';i.period_ref='p1';i.authority.actions=['workforce.coverage.update'];i.coverage={competence_accepted:true,authority_current:true,period_ref:'p1',owner_acceptance_ref:'a1',independent_review_preserved:true};assert.equal(planPeople(i).result,'PLANNED_CONTRIBUTION');for(const key of Object.keys(i.coverage)){const c=structuredClone(i);delete c.coverage[key];assert.equal(planPeople(c).result,'BLOCKED');}});
test('internal staff requires actual authenticated recipient context',()=>{const i=base();i.method='internal';i.authority.actions=['communication.internal.send'];i.recipient={authenticated:true,authorized:true,role_context:'internal-staff',scope:i.scope};assert.equal(planPeople(i).result,'PLANNED_CONTRIBUTION');for(const change of [r=>r.role_context='external',r=>r.authenticated=false,r=>r.authorized=false,r=>r.scope='other']){const c=structuredClone(i);change(c.recipient);assert.equal(planPeople(c).reason,'recipient_scope');}});
const access=()=>{const expected={scope:'org:test',person_ref:'person:synthetic',operation:'access.apply',correlation_id:'request:1',grant_revision:'r1',resource_ref:'surface:internal',permission_scope:'read:guidance'};return {expected,grant:{...expected,accepted:true,current:true},receipt:{...expected,status:'OBSERVED',outcome:'APPLIED',current:true,evidence_ref:'e1'}};};
test('requested access and attendance do not imply applied access',()=>{const a=access();a.receipt.status='REQUESTED';assert.equal(observeAccess(a.receipt,a.grant,a.expected),'UNKNOWN');a.receipt.status='OBSERVED';delete a.grant.accepted;assert.equal(observeAccess(a.receipt,a.grant,a.expected),'UNKNOWN');});
test('revoked scoped grant overrides historical applied snapshot',()=>{const a=access();a.grant.revoked=true;assert.equal(observeAccess(a.receipt,a.grant,a.expected),'REVOKED');});
test('exact correlated receipt and grant allow observed result',()=>{const a=access();assert.equal(observeAccess(a.receipt,a.grant,a.expected),'APPLIED');assert.equal(observeAccess(a.receipt,a.grant),'UNKNOWN');});
for(const key of ['scope','person_ref','operation','correlation_id','grant_revision','resource_ref','permission_scope']) test('access '+key+' mismatch remains unknown',()=>{const a=access();a.receipt[key]='other';assert.equal(observeAccess(a.receipt,a.grant,a.expected),'UNKNOWN');a.receipt[key]=a.expected[key];a.grant[key]='other';assert.equal(observeAccess(a.receipt,a.grant,a.expected),'UNKNOWN');});
test('invalid outcome blocks planning',()=>{const i=base();i.effect_status='imagined';assert.equal(planPeople(i).reason,'invalid_effect_status');});
test('metadata declares department root hard Core 0.5.3',()=>{const m=JSON.parse(readFileSync(new URL('../dev.woia/manifest.json',import.meta.url)));assert.equal(m.schema,'dev.woia.department-orchestrator/v1');assert.equal(m.authoring_profile,'thin');assert.deepEqual(m.requires_plugins,[{name:'woia-core',minimum_version:'0.5.3'}]);});

import Ajv2020 from 'ajv/dist/2020.js';
test('request schema validates context and rejects extra or unsupported input',()=>{const schema=JSON.parse(readFileSync(new URL('../skills/woia-people/references/people-request.schema.json',import.meta.url)));const v=new Ajv2020().compile(schema);assert.equal(v(base()),true);const i=base();i.dispatch=true;assert.equal(v(i),false);delete i.dispatch;i.method='pay';assert.equal(v(i),false);});

test('missing access destination never qualifies',()=>{const a=access();delete a.expected.resource_ref;assert.equal(observeAccess(a.receipt,a.grant,a.expected),'UNKNOWN');});
